package bean;

import java.util.List;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CPR.java
//  @ Date : 13/05/2014
//  @ Author : 
//
//




import javax.persistence.*;


public class CPRBean
{
	private List <OrdenCompraBean> ordenesP;
	private List <RodamientoBean> rodamientos;
	private List <RodamientoBean> listaComparativa ;
	
	public List<OrdenCompraBean> getOrdenesP() {
		return ordenesP;
	}
	public void setOrdenesP(List<OrdenCompraBean> ordenesP) {
		this.ordenesP = ordenesP;
	}
	public List<RodamientoBean> getRodamientos() {
		return rodamientos;
	}
	public void setRodamientos(List<RodamientoBean> rodamientos) {
		this.rodamientos = rodamientos;
	}
	public List <RodamientoBean> getListaComparativa() {
		return listaComparativa;
	}
	public void setListaComparativa(List <RodamientoBean> listaComparativa) {
		this.listaComparativa = listaComparativa;
	}
}
