package bean;

import java.util.Date;
import java.util.List;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factura.java
//  @ Date : 13/05/2014
//  @ Author : 
//
//

import javax.persistence.*;


@Entity
@Table(name="Factura")
public class FacturaBean
{
	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int numero;	
	private String estado;
	private Date fecha;
	@OneToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="factura_cliente")
	private ClienteBean cliente;
	@OneToOne
	@JoinColumn(name="factura_pedido")
	private OrdenPedidoBean pedido; 
	@Embedded
	private float descuento; 
	@OneToMany(cascade=CascadeType.ALL)
	@JoinColumn(name="factura_item")
	private List <ItemFacturaBean> items; 
	private float total;
	public float getTotal() {
		return total;
	}
	public void setTotal(float total) {
		this.total = total;
	}
	
	public List<ItemFacturaBean> getItems() {
		return items;
	}
	public void setItems(List<ItemFacturaBean> items) {
		this.items = items;
	}
	
	public OrdenPedidoBean getPedido() {
		return pedido;
	}
	public void setPedido(OrdenPedidoBean pedido) {
		this.pedido = pedido;
	}
	public int getNumero() {
		return numero;
	}
	public void setNumero(int numero) {
		this.numero = numero;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}
	public Date getFecha() {
		return fecha;
	}
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	public ClienteBean getCliente() {
		return cliente;
	}
	public void setCliente(ClienteBean cliente) {
		this.cliente = cliente;
	}
	public float getDescuento() {
		return descuento;
	}
	public void setDescuento(float descuento) {
		this.descuento = descuento;
	}
	
	
}
