package bean;

import javax.persistence.*;

import dto.ItemCotizacionDto;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemCotizacion.java
//  @ Date : 13/05/2014
//  @ Author : 
//
//


@Entity
@Table(name="ItemCotizacion")

public class ItemCotizacionBean
{
	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	private int numero; 

	@OneToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="item_rodamiento")
	private RodamientoBean rodamiento;
	private int cant;
	private float subtotal;
	
	public float getSubtotal() {
		return subtotal;
	}
	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}
	public RodamientoBean getRodamiento() {
		return rodamiento;
	}
	public void setRodamiento(RodamientoBean rodamiento) {
		this.rodamiento = rodamiento;
	}
	public int getCant() {
		return cant;
	}
	public void setCant(int cant) {
		this.cant = cant;
	}
	public ItemCotizacionBean(ItemCotizacionDto i) {
		super();
		RodamientoBean r=new RodamientoBean(i.getRodamiento());
		this.rodamiento = r;
		this.cant = i.getCant();
//		this.subtotal=i.getSubtotal();
	}
	
}
